export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// src/app/Administration/layout.tsx
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
    </>
  );
}

