export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>; // o un div, section, lo que quieras
}

